### ISSUE TITLE
When I run the examples in dcase_unit, the module named sed_eval in evaluation section can't finded.

### ISSUE THREAD

**Issue by dby124** [DCASE-REPO/dcase_util#2]
Traceback (most recent call last):
  File "D:/py_code/firstpython/venv/first_python/test.py", line 4, in <module>
    import sed_eval
ImportError: No module named sed_eval

**Comment by dby124** [comment]
After trying install the module named sed_eval via inputting "pip install sed_eval", the problem is solved.

**Comment by toni-heittola** [comment]
`sed_eval` is not used in `dcase_util`. Some of the provided example applications are using it for the evaluation, however, these examples are not part of toolbox. This is reason it is not included in the requirements.txt file.

**Comment by dby124** [comment]
OK，thank you very much.
