### ISSUE TITLE
Version Errors

### ISSUE THREAD

**Issue by SilverHawk2020** [DCASE-REPO/dcase_util#35]
Lines 302 to 312 should be like that (Add tf.compat.v1)
------------------------------------------
        config =tf.compat.v1.ConfigProto(
            inter_op_parallelism_threads=BLAS_thread_count
        )

        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
        import logging
        logging.getLogger('tensorflow').setLevel(logging.FATAL)

        with SuppressStdoutAndStderr():
            from keras import backend as k
            session =tf.compat.v1.Session()(config=config)
----------------------------------
https://github.com/DCASE-REPO/dcase_util/blob/0e35c3cf1aeb13d25a82ac0ea8a77d1b7f2eff62/dcase_util/keras/utils.py#L312

**Comment by toni-heittola** [comment]
This issue is related to Keras versions. This has been resolved in commit b72f46629468981339c43c25b720411f73e61851 by introducing tfkeras utilities to be used with Keras 2.x which is included in the TensorFlow framework.
