### ISSUE TITLE
Error while running event roll tutorial code with version 2.16

### ISSUE THREAD

**Issue by shubhr** [DCASE-REPO/dcase_util#36]
I am trying to run the event roll code from dcase repo and getting the error "QuadMesh' object has no attribute yaxis" for the line event_roll.plot()

**Comment by toni-heittola** [comment]
Did you get any line number inside dcase_util with the error? Which version of matplotlib you have? 
I just verified that the tutorial example (https://dcase-repo.github.io/dcase_util/tutorial_metadata.html#event-roll) works with my setup (I'm currently using matplotlib version 3.1.3)

**Comment by shubhr** [comment]
I got the  issue on this line 
 if self.label_list:
    ax.yaxis.set_label_position("right"). 
line number is 2240. My matplotlib version is 3.3.3

**Comment by toni-heittola** [comment]
This issue was related to librosa 0.8.0 and change what [librosa.display.specshow](https://github.com/librosa/librosa/issues/1180)  returns. The commit b76c97d47f13c5d7f3c849e7525a385ac62802e3 fixed this. Easiest way to fix this is to update to newest `dcase_util` version (>= v0.2.17).
