### ISSUE TITLE
Error when running the "asc_gmm.py" example

### ISSUE THREAD

**Issue by dangpzanco** [DCASE-REPO/dcase_util#5]
#### Description

Error when running the `asc_gmm.py` example on Windows 10, `asc_gmm_simple.py` runs just fine. Does it need to be modified before hand? Are there any extra steps that I did not understand?

I'm just reporting this because I think examples should be easy to use and learn from, it is not an urgent bug, but it should help newcomers (such as me) to get started with the lib. 

Thanks for your time developing this library.

#### Steps/Code to Reproduce
Run `python dcase_util\examples\asc_gmm.py`.

#### Expected Results
Unkown.

#### Actual Results

```
Daniel@DANIEL-ASUS D:\Documents\GitHub\dcase_util\examples
> python asc_gmm.py
[I] Acoustic Scene Classification Example / GMM
[E] Path: Unknown data type for paths.  (files.py:393)
NoneType: None
Traceback (most recent call last):
  File "asc_gmm.py", line 75, in <module>
    dcase_util.utils.Path().create(param['path'].values())
  File "D:\Programs\Miniconda3\lib\site-packages\dcase_util\utils\files.py", line 394, in create
    raise ValueError(message)
ValueError: Path: Unknown data type for paths.
```

#### Versions
```
>>> import platform; print(platform.platform())
Windows-10-10.0.16299-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.0.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 2.2.2
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.0
```

#### PS
Just in case you don't see it, I've also opened an [issue](https://github.com/TUT-ARG/DCASE2017-baseline-system/issues/22) on the DCASE2017-baseline-system repo. It is not related to this one, but occurs on the example code, too.

**Comment by toni-heittola** [comment]
This issue seems to concern only Python 3.7 on Windows. Commit 484a63ae66f13cadaaa584c5fdf861aea08cc06a should fix this.

DCASE2017-baseline-system is not actively maintained against newest version of external libraries as the development has been moved to `dcase_util`. However, I will take a look of that open issue once DCASE2018 is fully launched.

**Comment by toni-heittola** [comment]
This issue was closed as there was no follow up from author for at least 3 weeks. Feel free to reopen issue if needed.
